name: Docker

on:
  schedule:
    - cron: "40 7 * * *"
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  VERSION: "2.91"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: v2.2.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images using bake
        run: |
          VERSION=${VERSION} docker buildx bake \
            --file "docker-bake.hcl" \
            $([[ "${{ github.event_name }}" != "pull_request" ]] && echo "--push")

      - name: Sign published images
        if: github.event_name != 'pull_request'
        run: |
          docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/dnsmasq:latest >/dev/null
          cosign sign --yes ghcr.io/${{ github.repository_owner }}/dnsmasq:latest 
          cosign sign --yes ghcr.io/${{ github.repository_owner }}/dnsmasq:${VERSION}
